// src/svelte/LoginForm.svelte
<script>
  let email = "";
  let password = "";

  function handleSubmit() {
    console.log("Email:", email, "Password:", password);
  }
</script>

<form on:submit|preventDefault={handleSubmit}>
  <label for="email">Email:</label>
  <input type="email" id="email" bind:value={email} />
  <br />
  <label for="password">Password:</label>
  <input type="password" id="password" bind:value={password} />
  <br />
  <button type="submit">Login</button>
</form>

// vue-svelte-compare/src/vue/LoginForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <label for="email">Email:</label>
    <input type="email" id="email" v-model="email" />
    <br />
    <label for="password">Password:</label>
    <input type="password" id="password" v-model="password" />
    <br />
    <button type="submit">Login</button>
  </form>
</template>

<script>
export default {
  data() {
    return {
      email: "",
      password: "",
    };
  },
  methods: {
    handleSubmit() {
      console.log("Email:", this.email, "Password:", this.password);
    },
  },
};
</script>
